---
title: "norm-exploration"
author: "Björn Siepe"
date: "2022-12-20"
output: html_document
---

# Introduction
Here, we try to understand matrix norms a bit better by computing norms of difference matrices
and plotting the change of norms. 

# Change maximum edge

First, look at a changes when changing the largest parameters:
```{r}
beta <- as.matrix(read.table(header = FALSE, colClasses = "numeric", text = "
 0.2266407 0.0000000  0.0000000 -0.2668593  0.0000000 0.0000000
-0.7380388 0.2266407  0.0000000  0.0000000 -0.9288327 0.0000000
 0.0000000 0.0000000  0.2266407  0.9571318  0.2409225 0.5543485
 0.0000000 0.0000000  0.0000000  0.2266407 -0.7438448 0.0000000
 0.5214148 0.0000000  0.0000000  0.0000000  0.2266407 0.0000000
 0.0000000 0.0000000 -0.8903007  0.0000000  0.0000000 0.2266407"))

kappa <- as.matrix(read.table(header = FALSE, colClasses = "numeric", text = "
 1.0000000  0.0000000  0.0000000 0.0000000  0.4018933 0.3717013
 0.0000000  1.0000000  0.2266407 0.5527593 -0.2654634 0.2593779
 0.0000000  0.2266407  1.0000000 0.0000000 -0.3318945 0.3175423
 0.0000000  0.5527593  0.0000000 1.0000000  0.0000000 0.0000000
 0.4018933 -0.2654634 -0.3318945 0.0000000  1.0000000 0.0000000
 0.3717013  0.2593779  0.3175423 0.0000000  0.0000000 1.0000000"))
pcc <- -stats::cov2cor(kappa)

# Change by factor -2 to 2
max_change <- seq(-2,2, by = 0.1)
kap_new <- kappa
beta_new <- beta
pcc_new <- pcc

# Setup storage
beta_list <- list(beta_new)[rep(1, length(max_change))]
pcc_list <- list(pcc_new)[rep(1, length(max_change))]
bnorm_list <- list()
pnorm_list <- list()
bnorm_list[["l1"]] <- list()
bnorm_list[["maxdiff"]] <- list()
bnorm_list[["frob"]] <- list()
pnorm_list[["l1"]] <- list()
pnorm_list[["maxdiff"]] <- list()
pnorm_list[["frob"]] <- list()

# Change maximum value
for(i in seq_along(max_change)){
  b_ind <- which.max(abs(beta))
  p_ind <- which.max(abs(pcc))
  beta_list[[i]][b_ind] <- beta_list[[i]][b_ind]*max_change[i]
  pcc_list[[i]][p_ind] <- pcc_list[[i]][p_ind]*max_change[i]
  bnorm_list[["l1"]][[i]] <- norm(beta - beta_list[[i]], type = "F")
  bnorm_list[["maxdiff"]][[i]] <- max(abs(beta - beta_list[[i]]))
  bnorm_list[["frob"]][[i]] <- sum(abs(beta - beta_list[[i]]))
  pnorm_list[["l1"]][[i]] <- norm(pcc - pcc_list[[i]], type = "F")
  pnorm_list[["maxdiff"]][[i]] <- max(abs(pcc - pcc_list[[i]]))
  pnorm_list[["frob"]][[i]] <- sum(abs(pcc - pcc_list[[i]]))
}
bnorm_res <- as.data.frame(do.call("rbind", bnorm_list))
bnorm_res$mat <- rep("beta", 3)
pnorm_res <- as.data.frame(do.call("rbind", pnorm_list))
pnorm_res$mat <- rep("pcc",3)
norm_res <- rbind(bnorm_res, pnorm_res)

# Unnest
norm_res <- norm_res %>% 
  rownames_to_column(. ,var = "comp") %>% 
  mutate(comp = recode(comp, 
                       "l11" = "l1",
                       "maxdiff1" = "maxdiff",
                       "frob1" = "frob")) %>% 
  unnest(cols = starts_with("V"))

# change names to show change
names(norm_res) <- c("comp", max_change, "mat")

norm_res %>% 
  pivot_longer(cols = !c(comp, mat), names_to  = "change") %>% 
  mutate(change = as.numeric(change)) %>% 
  ggplot(aes(x = change, y = value, color = comp)) +
  geom_line() +
  facet_grid(mat~comp)+
  theme_minimal()+
  scale_color_okabe_ito()+
  labs(title = "Change of maximum beta value with certain factor",
       x = "Change Factor")



  
```


Now add random uniform noise
```{r}
change_noise <- seq(0,1, by = 0.05)
beta_list <- list(beta_new)[rep(1, length(change_noise))]
kappa_list <- list(kap_new)[rep(1, length(change_noise))]
bnorm_list <- list()
knorm_list <- list()
bnorm_list[["l1"]] <- list()
bnorm_list[["maxdiff"]] <- list()
bnorm_list[["frob"]] <- list()
knorm_list[["l1"]] <- list()
knorm_list[["maxdiff"]] <- list()
knorm_list[["frob"]] <- list()

# Add noise
for(i in seq_along(change_noise)){
  beta_list[[i]] <- beta_list[[i]] + runif(36, min = -change_noise[i], max = change_noise[i])
  kappa_list[[i]] <- kappa_list[[i]] + runif(36, min = -change_noise[i], max = change_noise[i])
  kappa_list <- lapply(kappa_list, Matrix::forceSymmetric)
  bnorm_list[["l1"]][[i]] <- norm(beta - beta_list[[i]], type = "F")
  bnorm_list[["maxdiff"]][[i]] <- max(abs(beta - beta_list[[i]]))
  bnorm_list[["frob"]][[i]] <- sum(abs(beta - beta_list[[i]]))
  knorm_list[["l1"]][[i]] <- norm(kappa - kappa_list[[i]], type = "F")
  knorm_list[["maxdiff"]][[i]] <- max(abs(kappa - kappa_list[[i]]))
  knorm_list[["frob"]][[i]] <- sum(abs(kappa - kappa_list[[i]]))
  
  
  
}
bnorm_res <- as.data.frame(do.call("rbind", bnorm_list))
bnorm_res$mat <- rep("beta", 3)
knorm_res <- as.data.frame(do.call("rbind", knorm_list))
knorm_res$mat <- rep("kappa",3)
norm_res <- rbind(bnorm_res, knorm_res)

norm_res <- norm_res %>% 
  rownames_to_column(. ,var = "comp") %>% 
    mutate(comp = recode(comp, 
                       "l11" = "l1",
                       "maxdiff1" = "maxdiff",
                       "frob1" = "frob")) %>% 
  unnest(cols = starts_with("V"))

# change names to show change
names(norm_res) <- c("comp", change_noise, "mat")

norm_res %>% 
  pivot_longer(cols = !c(comp, mat), names_to  = "change") %>% 
  mutate(change = as.numeric(change)) %>% 
  ggplot(aes(x = change, y = value, color = comp)) +
  geom_line() +
  facet_grid(mat~comp)+
  theme_minimal()+
  scale_color_okabe_ito()+
  labs(title = "Change of maximum beta value with uniform noise",
       x = "Interval width of uniform noise",
       caption = "Example : 0.5 means runif(n, -0.25, 0.5)")



```

Now add t-noise (more extreme values)
```{r}
change_t <- seq(1, 50, by = 1)
beta_list <- list(beta_new)[rep(1, length(change_t))]
kappa_list <- list(kap_new)[rep(1, length(change_t))]
bnorm_list <- list()
knorm_list <- list()
bnorm_list[["l1"]] <- list()
bnorm_list[["maxdiff"]] <- list()
bnorm_list[["frob"]] <- list()
knorm_list[["l1"]] <- list()
knorm_list[["maxdiff"]] <- list()
knorm_list[["frob"]] <- list()

# Add noise
for(i in seq_along(change_noise)){
  beta_list[[i]] <- beta_list[[i]] + rt(36, df = change_t[i])
  kappa_list[[i]] <- kappa_list[[i]] + rt(36, df = change_t[i])
  kappa_list <- lapply(kappa_list, Matrix::forceSymmetric)
  bnorm_list[["l1"]][[i]] <- norm(beta - beta_list[[i]], type = "F")
  bnorm_list[["maxdiff"]][[i]] <- max(abs(beta - beta_list[[i]]))
  bnorm_list[["frob"]][[i]] <- sum(abs(beta - beta_list[[i]]))
  knorm_list[["l1"]][[i]] <- norm(kappa - kappa_list[[i]], type = "F")
  knorm_list[["maxdiff"]][[i]] <- max(abs(kappa - kappa_list[[i]]))
  knorm_list[["frob"]][[i]] <- sum(abs(kappa - kappa_list[[i]]))
  
  
  
}
bnorm_res <- as.data.frame(do.call("rbind", bnorm_list))
bnorm_res$mat <- rep("beta", 3)
knorm_res <- as.data.frame(do.call("rbind", knorm_list))
knorm_res$mat <- rep("kappa",3)
norm_res <- rbind(bnorm_res, knorm_res)

norm_res <- norm_res %>% 
  rownames_to_column(. ,var = "comp") %>% 
    mutate(comp = recode(comp, 
                       "l11" = "l1",
                       "maxdiff1" = "maxdiff",
                       "frob1" = "frob")) %>% 
  unnest(cols = starts_with("V"))

# change names to show change
names(norm_res) <- c("comp", change_noise, "mat")

norm_res %>% 
  pivot_longer(cols = !c(comp, mat), names_to  = "change") %>% 
  mutate(change = as.numeric(change)) %>% 
  ggplot(aes(x = change, y = value, color = comp)) +
  geom_line() +
  facet_grid(mat~comp)+
  theme_minimal()+
  scale_color_okabe_ito()+
  labs(title = "Change of maximum beta value with student-t noise",
       x = "Degrees of freedom", 
       caption = "n = 50")
```


